---
title: "LIBD Globus"
---

This website contains the latest list of Globus Share Endpoints created by the LIBD Data Science Team 1. For more information about how to use Globus check the [JHPCE Globus tutorial website](https://jhpce.jhu.edu/knowledge-base/using-globus-to-transfer-files/).

```{r 'create_index', echo = FALSE}
create_index <- function(dirname, website) {
    
    html <- paste0(
'<html>
<head>
<meta http-equiv="refresh" content="0;url=\'', website, '\'">
</head>
</html>
'       
    )
        
## This didn't work...      
# glue:glue(
# '<html>
# <head>
# <meta http-equiv="refresh" content="0;url=\'{website}\'">
# </head>
# </html>
# '
#     )
    dirname_valid <- gsub('#', '_', dirname)
    
    dir.create(dirname_valid, showWarnings = FALSE)
    index <- file.path(dirname_valid, 'index.html')
    cat(html, file = index)
    
    ## Make link
    markdown_link <- glue::glue('* [`{dirname}`]({dirname_valid}/index.html)')
    return(markdown_link)
}
```

```{r 'indexes', results = 'asis', echo = FALSE}
# /dcl01/lieber/ajaffe/lab/brainseq_phase2/preprocessed_data/DLPFC_RiboZero/brainseq/dlpfc/merged_fastq/ (original)
# /dcs04/lieber/lcolladotor/BrainSEQ_LIBD001/brainseq_phase2/preprocessed_data/DLPFC_RiboZero/brainseq/dlpfc/merged_fastq/ (since 2024-02-07)
create_index('jhpce#bsp2-dlpfc', 'https://app.globus.org/file-manager?origin_id=daf68420-f9de-42dd-a81b-3840fa43149d&origin_path=%2F')

# /dcl01/lieber/ajaffe/lab/brainseq_phase2/preprocessed_data/Hippo_RiboZero/brainseq/hippo/merged_fastq/ (original)
# /dcs04/lieber/lcolladotor/BrainSEQ_LIBD001/brainseq_phase2/preprocessed_data/Hippo_RiboZero/brainseq/hippo/merged_fastq/ (since 2024-02-07)
create_index('jhpce#bsp2-hippo', 'https://app.globus.org/file-manager?origin_id=83d37357-274b-4cd5-bb2a-5dbd2be655c8&origin_path=%2F')

# /dcs04/lieber/lcolladotor/BrainSEQ_LIBD001/brainseq_phase2/preprocessed_data/DLPFC_RiboZero/HISAT2_out/
create_index('jhpce#bsp2-dlpfc-bam', 'https://app.globus.org/file-manager?origin_id=836aeb49-f31c-45a9-b9ad-9fa860343ded&origin_path=%2F')

# /dcl01/lieber/ajaffe/lab/brainseq_phase2/preprocessed_data/Hippo_RiboZero/HISAT2_out/ (original)
# /dcs04/lieber/lcolladotor/BrainSEQ_LIBD001/brainseq_phase2/preprocessed_data/Hippo_RiboZero/HISAT2_out/ (since 2024-02-07)
create_index('jhpce#bsp2-hippo-bam', 'https://app.globus.org/file-manager?origin_id=2fe34b7e-1dbf-11ea-b955-0e16720bb42f&origin_path=%2F')

# /dcl01/lieber/ajaffe/CellSorting/RNAseq_pipeline/ (original)
# /dcl01/lieber/ajaffe/CellSorting/RNAseq_pipeline/ (since 2024-02-07)
create_index('jhpce#brainepi-cellsorted', 'https://app.globus.org/file-manager?origin_id=1d1096ba-cf44-11e9-939e-02ff96a5aa76&origin_path=%2F')

# /dcl01/lieber/ajaffe/lab/brain-epigenomics/brainseq_pipeline/polyA_unstranded/ (original)
# /dcs05/lieber/liebercentral/wgbsPrice2019_LIBD001/brainseq_pipeline/polyA_unstranded/ (since 2024-02-07)
create_index('jhpce#brainepi-polyA', 'https://app.globus.org/file-manager?origin_id=5b3ab2c2-cf44-11e9-98e2-0a63aa6b37da&origin_path=%2F')

# /dcl01/lieber/ajaffe/Amanda/NucVsCyt/pipeline_output/ (original)
## I can't find the data under /dcs05/lieber/liebercentral/dcl01Legacy_LIBD001/Amanda/ (2024-02-07)
# /dcs05/lieber/liebercentral/dcl01Legacy_LIBD001/Amanda/BrainRNACompartments/not_in_paper/NucVsCyt/pipeline_output/ (seems like it's this one, 2024-02-07)
create_index('jhpce#fractionRNA', 'https://app.globus.org/file-manager?origin_id=f3cb5692-f3aa-11e9-be92-02fcc9cdd752&origin_path=%2F')

# /dcl02/lieber/ajaffe/NatComm_StemCellData/
create_index('NatComm_StemCellData', 'https://app.globus.org/file-manager?origin_id=ce314562-0ae4-11ea-be9a-02fcc9cdd752&origin_path=%2F')

# /dcl02/lieber/ajaffe/NatNeuro_TCF4_Data/
create_index('NatNeuro_TCF4_Data', 'https://app.globus.org/file-manager?origin_id=a79ed5e2-0bdc-11ea-be9b-02fcc9cdd752&origin_path=%2F')

# /dcl02/lieber/ajaffe/SpatialTranscriptomics/HumanPilot/10X/
create_index('jhpce#HumanPilot10x', 'https://app.globus.org/file-manager?origin_id=ae756c8c-c211-11ea-8f24-0a21f750d19b&origin_path=%2F')

# /dcl01/ajaffe/data/lab/singleCell/10x_pilot/FASTQ/ (original)
# /dcs04/lieber/lcolladotor/rawDataTDSC_LIBD001/raw-data/2021-10-15_Tran2021_published (since 2024-02-07)
create_index("jhpce#tran2021", "https://app.globus.org/file-manager?origin_id=e4e30efc-f166-11eb-ab64-d195c983855c&origin_path=%2F")

# /dcs04/lieber/lcolladotor/deconvolution_LIBD4030/TREG_paper/
create_index("jhpce#TREG_paper", "https://app.globus.org/file-manager?origin_id=9884e5b8-aae9-11ec-bade-cd8db799a66a&origin_path=%2F")

# /dcs04/lieber/lcolladotor/spatialDLPFC_LIBD4035/spatialDLPFC/
create_index("jhpce#spatialDLPFC", "https://app.globus.org/file-manager?origin_id=6cd81564-ed47-11ec-8358-cd84b862b754&origin_path=%2F")

# /dcs04/lieber/lcolladotor/deconvolution_LIBD4030/DLPFC_snRNAseq/
create_index("jhpce#DLPFC_snRNAseq", "https://app.globus.org/file-manager?origin_id=6f9322c4-5eaf-11ed-b0b5-bfe7e7197080&origin_path=%2F")

# /dcs04/lieber/lcolladotor/with10x_LIBD001/Visium_IF_AD/
create_index("jhpce#Visium_SPG_AD", "https://app.globus.org/file-manager?origin_id=03252306-c509-11ed-961f-4b6fcc022e5a&path=%2F")

# /dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/
create_index("jhpce#spatial_NAc", "https://app.globus.org/file-manager?origin_id=b8faf5f2-d319-11ed-8ebb-fdf94a47aaa3&path=%2F")

# /dcs04/lieber/marmaypag/pilotLS_LIBD1070/snRNAseq_mouse/
create_index("jhpce#septum_lateral", "https://app.globus.org/file-manager?origin_id=4a246882-1209-11ee-bdd3-a3018385fcef&path=%2F")

# /dcl02/lieber/ajaffe/Roche_Habenula/preprocessed_data/FASTQ/
create_index("jhpce#habenulaPilotbulkRNAseq", "https://app.globus.org/file-manager?origin_id=4624b994-6b7a-4a70-b504-1615411a74e5&origin_path=%2F")

# /dcs04/lieber/lcolladotor/pilotHb_LIBD001/Roche_Habenula/raw-data/FASTQ_snRNAseq/
create_index("jhpce#habenulaPilotsnRNAseq", "https://app.globus.org/file-manager?origin_id=3727999a-15bd-41ca-bf79-8a7602dd0ffa&origin_path=%2F")

# /dcs04/lieber/lcolladotor/pilotHb_LIBD001/Roche_Habenula/raw-data/RNAscope_images/
create_index("jhpce#habenulaPilotRNAscope", "https://app.globus.org/file-manager?origin_id=efc055d5-7686-4957-814c-89e1392d4f42&origin_path=%2F")

# /dcs04/lieber/lcolladotor/deconvolution_LIBD4030/Human_DLPFC_Deconvolution/raw-data/bulkRNA/
create_index("jhpce#humanDeconvolutionBulkRNAseq", "https://app.globus.org/file-manager?origin_id=17ea5635-440c-4d4d-9b20-092463b1bdc4&origin_path=%2F")

# /dcs04/lieber/lcolladotor/deconvolution_LIBD4030/Human_DLPFC_Deconvolution/raw-data/RNAscope_images/
create_index("jhpce#humanDeconvolutionRNAScope", "https://app.globus.org/file-manager?origin_id=211e02e0-1fe4-4f48-8e43-371d3fbdf5da&origin_path=%2F")

# /dcs05/lieber/lcolladotor/visiumStitched_LIBD1070/visiumStitched_brain
create_index("jhpce#visiumStitched_brain", "https://app.globus.org/file-manager?origin_id=ed98ea3b-1f5b-4ef9-ba0d-9351abcc05e7&origin_path=%2F")

# /dcs04/lieber/marmaypag/ls_molecular-profiling_LIBD1070/ls_molecular-profiling/processed-data/globus/
create_index("jhpce#ls_molecular-profiling_sce", "https://app.globus.org/file-manager?origin_id=4a94e057-0063-491f-b735-6fc06a136f9e&origin_path=%2F")
```

For the following Globus share endpoints you need to request access given the type of data being shared.

```{r 'indexes_private', results = 'asis', echo = FALSE}
# /dcl01/ajaffe/data/lab/brainseq_phase1/preprocessed_data/HISAT2_out/ (original)
# /dcs04/lieber/lcolladotor/BrainSEQ_LIBD001/brainseq_phase1/preprocessed_data/HISAT2_out/ (since 2024-02-07)
create_index('jhpce#bsp1-bam', 'mailto:AndrewEJaffe@gmail.com')

# /dcl01/ajaffe/data/lab/brainseq_phase1/count_data/ (original)
# /dcs04/lieber/lcolladotor/BrainSEQ_LIBD001/brainseq_phase1/count_data/ (since 2024-02-07)
create_index('jhpce#bsp1-count', 'mailto:AndrewEJaffe@gmail.com')

# /dcl01/ajaffe/data/lab/brainseq_phase1/genotype_data/ (original)
# /dcs04/lieber/lcolladotor/BrainSEQ_LIBD001/brainseq_phase1/genotype_data/ (since 2024-02-07)
create_index('jhpce#bsp1-genotype', 'mailto:AndrewEJaffe@gmail.com')

# /dcl01/lieber/RNAseq/Datasets/BrainSeq_hg38/Phase2/Genotype/ (original)
# /dcs05/lieber/liebercentral/libdDatasets_LIBD001/BrainSeq_hg38/Phase2/Genotype/ (since 2024-02-07)
create_index('brainseq_phase2_genotypes', 'mailto:AndrewEJaffe@gmail.com')

# TODO by Ryan
create_index('WeberDivecha2023_locus_coeruleus', 'mailto:keri.martinowich@libd.org')

# /dcs04/lieber/lcolladotor/pilotHb_LIBD001/Roche_Habenula/processed-data/08_bulk_snpPC/
create_index("jhpce#habenulaPilotbulkDNAgenotype", "mailto:Kristen.Maynard@libd.org")
```
